### PR TITLE
added sticky roles

### PR DESCRIPTION
**Pull request by NxSaroj**
add sticky roles, /sticky config command, :)
note - i have not created  new files for guildmember add & guildmember removed, merged them in previous ones

### CODE REVIEW

**Comment by JustShush** [comment]
What exactly are sticky role? can you give me a small description?

**Comment by NxSaroj** [comment]
when any user leaves it store all his roles & if he rejoin his previous roles will be added

**Comment by JustShush** [comment]
BTW i closed this cuz the command didnt work so ya <3

**Comment by NxSaroj** [comment]
Ah, It should have worked, will request a new pull after verifying it

**Comment by JustShush** [comment]
give me your discord or join the support server so we can talk, i like the idea and i like that you are still interested in it <3

**Comment by NxSaroj** [comment]
Sure! We have talked earlier, TheAltSyst

**Pull request closed without merging**
